name: demo cicd
on:
 push:
 branches:
  -main
 jobs:
  deploy:
   runs-on: ubuntu-latest
   
   
 steps:
 -uses: actions/checkout@v2
 
 -name: Build
 run: |
  mkdir public
  cp test-cicd.html public/
  
  -name: deploy
  uses: adress of
  with:
  branch:gh-pages
  folder:public
